export const editorStyles = {
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
  },
  modal: {
    backgroundColor: '#1e1e1e',
    border: '1px solid #444',
    borderRadius: 8,
    display: 'flex',
    flexDirection: 'column' as const,
    width: '85vw',
    height: '80vh',
    maxWidth: 1100,
    maxHeight: 800,
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 16px',
    backgroundColor: '#252526',
    borderBottom: '1px solid #333',
    gap: 12,
  },
  headerTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#e0e0e0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    flex: 1,
  },
  headerPath: {
    fontSize: 11,
    color: '#888',
    marginLeft: 8,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  headerBtns: {
    display: 'flex',
    gap: 6,
    alignItems: 'center',
    flexShrink: 0,
  },
  btn: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '5px 12px',
    fontSize: 12,
    border: '1px solid #555',
    borderRadius: 4,
    background: '#353535',
    color: '#ccc',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  btnPrimary: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '5px 12px',
    fontSize: 12,
    border: 'none',
    borderRadius: 4,
    background: '#0078d4',
    color: '#fff',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  btnDanger: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '5px 12px',
    fontSize: 12,
    border: '1px solid #555',
    borderRadius: 4,
    background: '#353535',
    color: '#ef5350',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  editorContainer: {
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
    position: 'relative' as const,
  },
  lineNumbers: {
    width: 50,
    backgroundColor: '#1a1a1a',
    borderRight: '1px solid #333',
    overflow: 'hidden',
    padding: '10px 0',
    fontFamily: "'Consolas', 'Monaco', 'Courier New', monospace",
    fontSize: 13,
    lineHeight: '20px',
    color: '#555',
    textAlign: 'right' as const,
    userSelect: 'none' as const,
    flexShrink: 0,
  },
  lineNumber: {
    paddingRight: 8,
    paddingLeft: 4,
    height: 20,
    lineHeight: '20px',
  },
  textareaWrapper: {
    flex: 1,
    position: 'relative' as const,
    overflow: 'hidden',
  },
  textarea: {
    position: 'absolute' as const,
    inset: 0,
    width: '100%',
    height: '100%',
    padding: '10px 12px',
    fontFamily: "'Consolas', 'Monaco', 'Courier New', monospace",
    fontSize: 13,
    lineHeight: '20px',
    backgroundColor: 'transparent',
    color: '#d4d4d4',
    border: 'none',
    outline: 'none',
    resize: 'none' as const,
    whiteSpace: 'pre' as const,
    overflowWrap: 'normal' as const,
    overflow: 'auto',
    zIndex: 2,
    caretColor: '#fff',
    boxSizing: 'border-box' as const,
    tabSize: 4,
  },
  highlightPre: {
    position: 'absolute' as const,
    inset: 0,
    padding: '10px 12px',
    fontFamily: "'Consolas', 'Monaco', 'Courier New', monospace",
    fontSize: 13,
    lineHeight: '20px',
    color: 'transparent',
    whiteSpace: 'pre' as const,
    overflowWrap: 'normal' as const,
    overflow: 'auto',
    pointerEvents: 'none' as const,
    zIndex: 1,
    boxSizing: 'border-box' as const,
    tabSize: 4,
    margin: 0,
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px 16px',
    backgroundColor: '#252526',
    borderTop: '1px solid #333',
    fontSize: 11,
    color: '#888',
  },
  loading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    color: '#888',
    gap: 8,
    fontSize: 14,
  },
  saveAsOverlay: {
    position: 'fixed' as const,
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3000,
  },
  saveAsDialog: {
    backgroundColor: '#2d2d2d',
    border: '1px solid #555',
    borderRadius: 6,
    padding: 20,
    minWidth: 400,
    color: '#ccc',
  },
  saveAsTitle: {
    fontSize: 14,
    fontWeight: 600,
    marginBottom: 12,
  },
  saveAsInput: {
    width: '100%',
    padding: '6px 8px',
    fontSize: 13,
    border: '1px solid #555',
    borderRadius: 4,
    backgroundColor: '#1e1e1e',
    color: '#ccc',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  saveAsBtns: {
    display: 'flex',
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: 14,
  },
  unsavedDot: {
    display: 'inline-block',
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: '#ffab40',
    marginLeft: 8,
    verticalAlign: 'middle',
  },
};
