import { describe, expect, it } from 'vitest';

import { embedGCodeThumbnails } from './gcodeThumbnails';

describe('G-code thumbnails', () => {
  it('embeds thumbnail blocks inside the slicer header', () => {
    const gcode = [
      '; HEADER_BLOCK_START',
      '; Generated by Cindr3D Slicer',
      '; HEADER_BLOCK_END',
      'G28',
    ].join('\n');

    const embedded = embedGCodeThumbnails(gcode, [
      { width: 32, height: 32, format: 'png', data: 'iVBORw0KGgo=' },
      { width: 300, height: 300, format: 'png', data: 'iVBORw0KGgoAAAANSUhEUgAAAAE=' },
    ]);

    expect(embedded.indexOf('; thumbnail begin 32x32')).toBeGreaterThan(embedded.indexOf('; HEADER_BLOCK_START'));
    expect(embedded.indexOf('; thumbnail begin 300x300')).toBeGreaterThan(embedded.indexOf('; thumbnail begin 32x32'));
    expect(embedded.indexOf('; thumbnail end')).toBeLessThan(embedded.indexOf('; HEADER_BLOCK_END'));
    expect(embedded).toContain('G28');
  });

  it('replaces existing thumbnail blocks instead of duplicating them', () => {
    const gcode = [
      '; HEADER_BLOCK_START',
      '; thumbnail begin 32x32 1',
      '; old',
      '; thumbnail end',
      '; HEADER_BLOCK_END',
      'G28',
    ].join('\n');

    const embedded = embedGCodeThumbnails(gcode, [
      { width: 32, height: 32, format: 'png', data: 'newdata=' },
    ]);

    expect(embedded).not.toContain('; old');
    expect(embedded.match(/;\s*thumbnail begin/g)).toHaveLength(1);
    expect(embedded).toContain('; newdata=');
  });
});
